package persistencia.entidad;
// Generated 16-may-2018 17:19:11 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * NuevoSerial generated by hbm2java
 */
public class NuevoSerial  implements java.io.Serializable {


     private int id;
     private Date fecha;
     private long serial;
     private int control;
     private String agencia;

    public NuevoSerial() {
    }

    public NuevoSerial(int id, Date fecha, long serial, int control, String agencia) {
       this.id = id;
       this.fecha = fecha;
       this.serial = serial;
       this.control = control;
       this.agencia = agencia;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public long getSerial() {
        return this.serial;
    }
    
    public void setSerial(long serial) {
        this.serial = serial;
    }
    public int getControl() {
        return this.control;
    }
    
    public void setControl(int control) {
        this.control = control;
    }
    public String getAgencia() {
        return this.agencia;
    }
    
    public void setAgencia(String agencia) {
        this.agencia = agencia;
    }




}


