package persistencia.entidad;
// Generated 16-may-2018 17:19:11 by Hibernate Tools 4.3.1



/**
 * RuletaActiva generated by hbm2java
 */
public class RuletaActiva  implements java.io.Serializable {


     private int numero;
     private String numAnimalito;
     private String animalito;
     private String archivo;
     private int flag;

    public RuletaActiva() {
    }

	
    public RuletaActiva(int numero, String numAnimalito, String animalito, int flag) {
        this.numero = numero;
        this.numAnimalito = numAnimalito;
        this.animalito = animalito;
        this.flag = flag;
    }
    public RuletaActiva(int numero, String numAnimalito, String animalito, String archivo, int flag) {
       this.numero = numero;
       this.numAnimalito = numAnimalito;
       this.animalito = animalito;
       this.archivo = archivo;
       this.flag = flag;
    }
   
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public String getNumAnimalito() {
        return this.numAnimalito;
    }
    
    public void setNumAnimalito(String numAnimalito) {
        this.numAnimalito = numAnimalito;
    }
    public String getAnimalito() {
        return this.animalito;
    }
    
    public void setAnimalito(String animalito) {
        this.animalito = animalito;
    }
    public String getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(String archivo) {
        this.archivo = archivo;
    }
    public int getFlag() {
        return this.flag;
    }
    
    public void setFlag(int flag) {
        this.flag = flag;
    }




}


