package persistencia.entidad;
// Generated 16-may-2018 17:19:11 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RuletaActivaResultado generated by hbm2java
 */
public class RuletaActivaResultado  implements java.io.Serializable {


     private Long idResult;
     private int idRuletaActiva;
     private Date fechaResult;
     private String resultado;

    public RuletaActivaResultado() {
    }

    public RuletaActivaResultado(int idRuletaActiva, Date fechaResult, String resultado) {
       this.idRuletaActiva = idRuletaActiva;
       this.fechaResult = fechaResult;
       this.resultado = resultado;
    }
   
    public Long getIdResult() {
        return this.idResult;
    }
    
    public void setIdResult(Long idResult) {
        this.idResult = idResult;
    }
    public int getIdRuletaActiva() {
        return this.idRuletaActiva;
    }
    
    public void setIdRuletaActiva(int idRuletaActiva) {
        this.idRuletaActiva = idRuletaActiva;
    }
    public Date getFechaResult() {
        return this.fechaResult;
    }
    
    public void setFechaResult(Date fechaResult) {
        this.fechaResult = fechaResult;
    }
    public String getResultado() {
        return this.resultado;
    }
    
    public void setResultado(String resultado) {
        this.resultado = resultado;
    }




}


