package persistencia.entidad;
// Generated 16-may-2018 17:19:11 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RuletaActivaHoras generated by hbm2java
 */
public class RuletaActivaHoras  implements java.io.Serializable {


     private Integer id;
     private String descripcion;
     private Date hora;
     private String horaNum;

    public RuletaActivaHoras() {
    }

    public RuletaActivaHoras(String descripcion, Date hora, String horaNum) {
       this.descripcion = descripcion;
       this.hora = hora;
       this.horaNum = horaNum;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public String getHoraNum() {
        return this.horaNum;
    }
    
    public void setHoraNum(String horaNum) {
        this.horaNum = horaNum;
    }


    public String sorteos(){
        StringBuilder salida = new StringBuilder();
        salida.append(descripcion); 
        salida.append(hora);
        return salida.toString();
    }

}


