package persistencia.entidad;
// Generated 16-may-2018 17:19:11 by Hibernate Tools 4.3.1



/**
 * TotalesJugadas generated by hbm2java
 */
public class TotalesJugadas  implements java.io.Serializable {


     private Long id;
     private long numTicket;
     private String serial;
     private String fecha;
     private long total;

    public TotalesJugadas() {
    }

    public TotalesJugadas(long numTicket, String serial, String fecha, long total) {
       this.numTicket = numTicket;
       this.serial = serial;
       this.fecha = fecha;
       this.total = total;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getNumTicket() {
        return this.numTicket;
    }
    
    public void setNumTicket(long numTicket) {
        this.numTicket = numTicket;
    }
    public String getSerial() {
        return this.serial;
    }
    
    public void setSerial(String serial) {
        this.serial = serial;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public long getTotal() {
        return this.total;
    }
    
    public void setTotal(long total) {
        this.total = total;
    }




}


