package persistencia.entidad;
// Generated 16-may-2018 17:19:11 by Hibernate Tools 4.3.1



/**
 * UsuariosLotto generated by hbm2java
 */
public class UsuariosLotto  implements java.io.Serializable {


     private String nombreUsuario;
     private String claveUsuario;
     private String nombre;
     private String apellido;
     private String sexo;
     private int idUsuarios;

    public UsuariosLotto() {
    }

    public UsuariosLotto(String nombreUsuario, String claveUsuario, String nombre, String apellido, String sexo, int idUsuarios) {
       this.nombreUsuario = nombreUsuario;
       this.claveUsuario = claveUsuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.sexo = sexo;
       this.idUsuarios = idUsuarios;
    }
   
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getClaveUsuario() {
        return this.claveUsuario;
    }
    
    public void setClaveUsuario(String claveUsuario) {
        this.claveUsuario = claveUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public int getIdUsuarios() {
        return this.idUsuarios;
    }
    
    public void setIdUsuarios(int idUsuarios) {
        this.idUsuarios = idUsuarios;
    }




}


